wok:
  files:
    spyced-test-01:
      source: test-01
      spyces:
        spyce:
          flavor: api
          implementation: tmpfile
        wget-1.9.1.tar.gz:
          flavor: url
          url: https://ftp.gnu.org/gnu/wget/wget-1.9.1.tar.gz
